### ISSUE TITLE
Postges SQL Error

### ISSUE THREAD

**Issue by pyongyan** [HarmanPreet-Singh-XYT/E-Commerce#4]
pg_restore: error: unsupported version (1.15) in file header

**Comment by HarmanPreet-Singh-XYT** [comment]
Hey i tried to restore the file through pgAdmin and found no issue restoring it, am running PostgreSQL 16 and pgAdmin 8.8.
after google, i found it can be PostgreSQL version issue, as you maybe getting the error due to older version of PostgreSQL, try updating it to version 16 if it isn't updated.
sources - 
https://github.com/pgadmin-org/pgadmin4/issues/7114
https://stackoverflow.com/questions/59455783/pg-restore-archiver-unsupported-version-1-14-in-file-header

**Comment by pyongyan** [comment]
Thank You For Your Response
Can You send me .env example
like backend url only or port also + i need conf idea which i can add in
etc/nginx/sites-available

**Comment by HarmanPreet-Singh-XYT** [comment]
for configuring backend url- you have pass env variable like this BACKEND_URL='https://vps.ovh.net:3500' or BACKEND_URL='http://localhost:3000' if using locally, if backend server does not have SSL Certificate then use http not https. You have to mention the port with URL, if deploying using nginx, it has to be figured out as this project isn't deployed using nginx and i might take time to tell you the confs related to it as i need to learn it. 
example .env
[env.txt](https://github.com/user-attachments/files/16709207/env.txt)

**Comment by pyongyan** [comment]
Thanks, I'll check it out.
